#
# Makefile for the sw_touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SW_TOUCHSCREEN_GT9XX_BPI_TS)          += gt9xx_bpi_ts.o
gt9xx_bpi_ts-objs := goodix_tool.o gt9xx_update.o gt9xx.o

